# Generated by Django 5.2.5 on 2025-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=512, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('results', models.JSONField(default=dict)),
                ('raw_html', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['url', '-fetched_at'], name='audits_webs_url_fe6115_idx')],
            },
        ),
    ]
