# Generated by Django 5.2.5 on 2025-09-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteaudit',
            name='raw_html',
        ),
    ]
