# Generated by Django 5.2.5 on 2025-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_remove_websiteaudit_raw_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteaudit',
            name='rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='websiteaudit',
            index=models.Index(fields=['url', 'rendered', '-fetched_at'], name='audits_webs_url_66a52d_idx'),
        ),
    ]
