# Generated by Django 4.2.24 on 2025-09-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_websiteaudit_results_websiteauditresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteauditresult',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
