# Generated by Django 4.2.24 on 2025-10-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_websiteauditresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteaudit',
            name='ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websiteaudit',
            name='raw',
            field=models.BooleanField(default=False),
        ),
    ]
